name: 'automated_testing_framework_plugin_firebase'
description: "Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase'
version: '5.0.2+7'

environment: 
  sdk: '>=2.19.0 <4.0.0'

dependencies: 
  automated_testing_framework: '^5.0.0+7'
  automated_testing_framework_models: '^2.0.10+3'
  automated_testing_framework_plugin_firebase_storage: '^5.0.1+6'
  convert: '^3.1.1'
  firebase_auth: '^4.2.10'
  firebase_core: '^2.7.1'
  firebase_database: '^10.0.15'
  firebase_storage: '^11.0.15'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.2.0+6'
  intl: '^0.18.0'
  json_class: '^2.1.6+1'
  logging: '^1.1.1'
  static_translations: '^2.1.2+6'
  uuid: '^3.0.7'

dependency_overrides: 
  intl: '^0.18.0'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
