name: automated_testing_framework_plugin_firebase
description: Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase

version: 1.0.14+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  automated_testing_framework: ^1.3.2+1
  automated_testing_framework_models: ^1.0.5+2
  automated_testing_framework_plugin_firebase_storage: ^1.0.10
  convert: ^2.1.1
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_database: ^4.4.0
  firebase_storage: ^5.2.0
  flutter:
    sdk: flutter
  form_validation: ^1.0.2
  intl: ^0.16.1
  json_class: ^1.0.6+1
  logging: ^0.11.4
  meta: ^1.2.4
  static_translations: ^1.0.3
  uuid: ^2.2.2

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
