name: 'automated_testing_framework_plugin_firebase'
description: "Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase'
version: '5.0.0+7'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+7'
  automated_testing_framework_models: '^2.0.9+4'
  automated_testing_framework_plugin_firebase_storage: '^5.0.0+6'
  convert: '^3.0.2'
  firebase_auth: '^3.4.1'
  firebase_core: '^1.19.1'
  firebase_database: '^9.0.18'
  firebase_storage: '^10.3.1'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+8'
  intl: '^0.17.0'
  json_class: '^2.1.2+7'
  logging: '^1.0.2'
  static_translations: '^2.1.1+5'
  uuid: '^3.0.6'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
