name: automated_testing_framework_plugin_firebase
description: Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase

version: 4.0.2+2

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.3.1+1
  automated_testing_framework_models: ^2.0.8+4
  automated_testing_framework_plugin_firebase_storage: ^4.0.1+3
  convert: ^3.0.1
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_database: ^9.0.11
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  intl: ^0.17.0
  json_class: ^2.1.2+4
  logging: ^1.0.2
  static_translations: ^2.1.1
  uuid: ^3.0.6

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
#   automated_testing_framework_plugin_firebase_storage:
#     path: ../automated_testing_framework_plugin_firebase_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
