name: automated_testing_framework_plugin_firebase
description: Library to use Google's Firebase Realtime Database as a storage mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase

version: 3.0.1-nullsafety

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.0.2
  automated_testing_framework_models: ^2.0.0+1
  automated_testing_framework_plugin_firebase_storage: ^3.0.0
  convert: ^3.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_database: ^7.0.0-dev.1
  firebase_storage: ^8.0.0
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  intl: ^0.17.0
  json_class: ^2.0.0
  logging: ">=0.11.4 <2.0.0"
  static_translations: ^2.0.0+1
  uuid: ^3.0.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models
#   automated_testing_framework_plugin_firebase_storage:
#     path: ../automated_testing_framework_plugin_firebase_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
